server:
  port: 8082
spring:
  application:
    name: account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
microservices:
  client-service:
    url: http://sofka-client-service:8081
logging:
  level:
    com.banking: INFO
    org.springframework.web: INFO
